Repository FRONT-END-BOOTCAMP-PLUS-3/obama, pull requests merged in 2025-02, with the labels that each got.

#24 Feat/9 회원 등록 기능 구현 및 테스트 코드 구현
  jest.config.js
  package-lock.json
  package.json
  src/app/components/auth/SignUpForm.tsx
  src/app/components/auth/useSignForm.tsx
  src/application/usecases/auth/SignUpUseCase.ts
  src/application/usecases/auth/dto/SignUpRequestDto.tsx
  src/domain/entities/User.ts
  src/domain/repositories/IUserRepository.ts
  src/infrastructure/repositories/auth/SbUserRepository.ts
  src/tests/repositories/SbUserRepository.test.ts
  src/tests/usecases/SignUpUsecase.test.ts
  src/tests/utils/convertCase.test.ts
  src/utils/auth/hashPassword.ts
  src/utils/convertCase.ts
  src/utils/supabase/server.ts
  src/utils/validate.ts
  tsconfig.json
Labels: :wrench: Setting, :sparkles: Feat

#31 Feat/#30 admin navbar 생성
  public/Icons/NavbarArrowDown.svg
  src/app/Home.styled.tsx
  src/app/admin/components/AdminLayoutContainer.tsx
  src/app/admin/components/Navbar/AdminNarvbar.styled.tsx
  src/app/admin/components/Navbar/AdminNavbar.tsx
  src/app/admin/components/Navbar/AdminNavbarItem.tsx
  src/app/admin/layout.tsx
  src/app/admin/smalltalk/balanceGames/page.tsx
  src/app/admin/smalltalk/topics/page.tsx
  src/app/admin/user/page.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/common/LayoutContainer.tsx
  src/data/adminNavbar.ts
  src/types/adminNavBar.d.ts
Labels: :sparkles: Feat

#33 Feat/25 signup 이메일 전송 기능 구현
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  src/__tests__/repositories/SbUserRepository.test.ts
  src/__tests__/testRedis.test.ts
  src/__tests__/usecases/SignUpUsecase.test.ts
  src/__tests__/utils/convertCase.test.ts
  src/app/api/send-email/route.ts
  src/application/.gitkeep
  src/application/auth/dtos/SignUpRequestDto.tsx
  src/application/auth/interfaces/IDuplicateEmailUseCase.ts
  src/application/auth/usecases/DuplicateEmailUseCase.ts
  src/application/auth/usecases/GenerateVerificationCodeUseCase.ts
  src/application/auth/usecases/SendEmailUseCase.ts
  src/application/auth/usecases/SignUpUseCase.ts
  src/application/common/usecases/PasswordHasherUseCase.ts
  src/application/common/usecases/UUIDGeneratorUseCase.ts
  src/application/common/usecases/interfaces/IPasswordHasherUseCase.ts
  src/application/common/usecases/interfaces/IUUIDGeneratorUseCase.ts
  src/application/usecases/auth/SignUpUseCase.ts
  src/components/auth/SignUpForm.tsx
  src/components/auth/useSignForm.tsx
  src/components/email/SendEmailTemplate.tsx
  src/config/env.ts
  src/domain/.gitkeep
  src/domain/emailVerification/EmailService.ts
  src/domain/repositories/IUserRepository.ts
  src/infrastructure/.gitkeep
  src/infrastructure/databases/redis/redisClient.ts
  src/infrastructure/databases/supabase/server.ts
  src/infrastructure/email-server/SMTPEmailService.ts
  src/infrastructure/repositories/auth/SbUserRepository.ts
  src/utils/auth/hashPassword.ts
  src/utils/auth/validate.ts
  src/utils/convertCase.ts
  src/utils/email/generateEmailHtml.tsx
  tsconfig.json
Labels: :sparkles: Feat

#37 Feat/36 smalltalk select 구현
  next.config.ts
  package-lock.json
  package.json
  public/Icons/dropdownTriangle.svg
  src/app/(anon)/smalltalks/select/page.tsx
  src/app/(anon)/smalltalks/select/select.Styled.tsx
  src/app/(user)/smalltalk/page.tsx
  src/app/api/smalltalkSubjects/route.ts
  src/application/common/usecases/smalltalkSubject/GetSmalltalkSubjectsUsecase.ts
  src/application/common/usecases/smalltalkSubject/dto/SmalltalkSubjectDto.ts
  src/components/common/Dropdown/Dropdown.Styled.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/LayoutContainer.tsx
  src/components/common/Navbar/NavBar.Styled.tsx
  src/domain/entities/SmalltalkSubject.ts
  src/domain/repositories/ISmalltalkSubjectRepository.ts
  src/infrastructure/databases/supabase/server.ts
  src/infrastructure/repositories/SbSmalltalkSubjectRepository.ts
  src/types/dropdown.d.ts
Labels: :sparkles: Feat

#38 Feat/35 verifiaction code 및 api연결
  package-lock.json
  package.json
  src/app/(anon)/signup/page.tsx
  src/app/(anon)/singup/page.tsx
  src/app/api/auth/check-email/route.ts
  src/app/api/auth/send-email/route.ts
  src/app/api/auth/signup/route.ts
  src/app/api/auth/verify-code/route.ts
  src/app/api/send-email/route.ts
  src/application/auth/usecases/CheckVerificationCodeUseCase.ts
  src/application/auth/usecases/DeleteVerificationCodeUseCase.ts
  src/application/auth/usecases/DuplicateEmailUseCase.ts
  src/application/auth/usecases/SendEmailUseCase.ts
  src/application/auth/usecases/SignUpUseCase.ts
  src/components/auth/SignUpForm.tsx
  src/components/auth/useSignForm.tsx
  src/components/auth/useSignUpForm.tsx
  src/components/email/SendEmailTemplate.tsx
  src/config/serverEnv.ts
  src/domain/entities/User.ts
  src/domain/entities/VerificationCode.ts
  src/domain/repositories/IVerificationRepository.ts
  src/infrastructure/databases/redis/redisClient.ts
  src/infrastructure/databases/supabase/server.ts
  src/infrastructure/email-server/SMTPEmailService.ts
  src/infrastructure/repositories/auth/RdVerificationRepository.ts
  src/infrastructure/repositories/auth/SbUserRepository.ts
  src/styles/email/sendEmailTemplate.tsx
  src/utils/auth/validate.ts
  src/utils/email/generateEmailHtml.tsx
Labels: :sparkles: Feat

#46 Style/#45 layoutcontainer 수정
  src/components/common/LayoutContainer.tsx
Labels: 💄Design

#55 Feat/#52 smalltalk openquestion 구현
  src/app/(anon)/smalltalks/[id]/page.tsx
  src/app/(anon)/smalltalks/select/page.tsx
  src/app/api/smalltalkOpenQuestion/route.ts
  src/application/smalltalk/smalltalkOpenQuestion/SmalltalkOpenQuestionUsecase.ts
  src/application/smalltalk/smalltalkOpenQuestion/dto/SmalltalkOpenQuestion.ts
  src/components/smaltalk/OpenQuestion.tsx
  src/components/smaltalk/Suggest.Styled.tsx
  src/domain/entities/SmalltalkOpenQuestion.ts
  src/domain/repositories/IsmalltalkOpenQuestionRepository.ts
  src/infrastructure/repositories/smalltalk/SbSmalltalkOpenQuestionRepository.ts
  src/types/openQuestionProps.ts
Labels: :sparkles: Feat

#59 Design/54- Styled loginpageUI Design
  package-lock.json
  src/app/(anon)/login/page.tsx
  src/app/(anon)/signup/page.tsx
  src/components/auth/LoginForm.Styled.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignUp.Styled.tsx
  src/components/auth/SignUpForm.tsx
Labels: 💄Design

#70 Hotfix/#60 api folder 구조 변경
  package-lock.json
  src/app/(anon)/smalltalks/select/page.tsx
  src/app/api/smalltalk/balancegameAnswer/route.ts
  src/app/api/smalltalk/balancegameQuestion/route.ts
  src/app/api/smalltalk/smalltalkOpenQuestion/route.ts
  src/app/api/smalltalks/[id]/route.ts
  src/app/api/smalltalks/select/route.ts
  src/components/smaltalk/BalanceGame.tsx
  src/components/smaltalk/OpenQuestion.tsx
Labels: 🚑!HotFix

#79 Design/#76 searchnbar UI
  src/app/(anon)/smalltalks/select/page.tsx
  src/components/admin/dropdown/Dropdown.tsx
  src/components/admin/searchbar/Searchbar.Styled.tsx
  src/components/admin/searchbar/Searchbar.tsx
  src/components/common/textField/TextField.Styled.tsx
  src/components/common/textField/TextField.tsx
  src/components/common/textField/styles.tsx
  src/components/smaltalk/dropdown/Dropdown.Styled.tsx
  src/components/smaltalk/dropdown/Dropdown.tsx
  src/types/textfield.d.ts
Labels: 💄Design

#85 Design/#80 pagenation component
  src/components/admin/pagenation/Pagenation.Style.tsx
  src/components/admin/pagenation/Pagenation.tsx
Labels: 💄Design

#87 Design/#86-balancegame-modal UI 생성
  src/components/admin/smalltalkmodal/SmalltalkModal.Style.tsx
  src/components/admin/smalltalkmodal/SmalltalkModal.tsx
  src/components/common/textField/TextField.Styled.tsx
  src/components/common/textField/styles.tsx
  src/types/textfield.d.ts
Labels: 💄Design

#89 Design/88 delete confirm modal UI 생성
  src/components/admin/deletemodal/ConfirmDeleteModal.style.tsx
  src/components/admin/deletemodal/ConfirmDeleteModal.tsx
Labels: 💄Design

#90 Design/82signup result page
  src/app/(anon)/signup/result/page.tsx
  src/app/NotFound.Styled.tsx
  src/app/not-found.tsx
  src/components/auth/SignUpResult.Styled.tsx
  src/components/auth/SignUpResult.tsx
  src/components/auth/useSignUpForm.tsx
Labels: 💄Design

#94 Design/#93 openquestion modal 생성 및 balancegame modal 이름 변경
  src/components/admin/balancegamemodal/BalancegameModal.Style.tsx
  src/components/admin/balancegamemodal/BalancegameModal.tsx
  src/components/admin/openquestionmodal/OpenQuestionModal.tsx
Labels: 💄Design

#95 Design/92 admin openquestion UI 구현 및 table component 생성 globalcss 수정
  src/app/admin/smalltalk/balancegame/page.tsx
  src/app/admin/smalltalk/openquestion/page.tsx
  src/app/admin/smalltalk/topics/page.tsx
  src/components/AdminOpenQuestion.Style.tsx
  src/components/admin/searchbar/Searchbar.Styled.tsx
  src/components/admin/table/Table.Style.tsx
  src/components/admin/table/Table.tsx
  src/mock/adminNavbar.ts
  src/styles/global.css
Labels: 💄Design

#97 Design/#96 관리자 유저 페이지 UI 구현
  src/app/admin/user/page.tsx
  src/components/admin/AdminLayoutContainer.tsx
  src/components/admin/pagenation/Pagenation.tsx
  src/components/admin/table/Table.Style.tsx
  src/components/admin/table/Table.tsx
Labels: 💄Design

#100 Design/#98 admin balancegame UI 구현, 모달 수정, pagenation 수정
  src/app/admin/smalltalk/balancegame/page.tsx
  src/app/admin/smalltalk/openquestion/page.tsx
  src/app/admin/user/page.tsx
  src/components/admin/AdminBalanceGame.Style.tsx
  src/components/admin/AdminOpenQuestion.Style.tsx
  src/components/admin/balancegamemodal/BalancegameModal.tsx
  src/components/admin/pagenation/Pagenation.Style.tsx
  src/components/admin/pagenation/Pagenation.tsx
Labels: 💄Design

#104 Feat/#103 admin open question db 연결
  src/app/admin/smalltalk/openquestion/page.tsx
  src/app/api/admin/smalltalk/openquestion/route.ts
  src/application/usecases/smalltalk/OpenQuestionUsecase.ts
  src/domain/repositories/smalltalk/IOpenQuestionRepository.ts
  src/infrastructure/repositories/smalltalk/SbOpenQuestionRepository.ts
Labels: :sparkles: Feat

#107 Feat/#105 open question 질문 등록
  src/app/admin/smalltalk/openquestion/page.tsx
  src/app/api/admin/smalltalk/openquestion/route.ts
  src/application/usecases/smalltalk/CreateOpenQuestionUsecase.ts
  src/components/admin/openquestionmodal/OpenQuestionModal.tsx
  src/domain/repositories/smalltalk/IOpenQuestionRepository.ts
  src/infrastructure/repositories/smalltalk/SbOpenQuestionRepository.ts
Labels: :sparkles: Feat

#109 Feat/#108 openquestion update
  src/app/admin/smalltalk/openquestion/page.tsx
  src/app/api/admin/smalltalk/openquestion/route.ts
  src/application/usecases/smalltalk/UpdateOpenQuestionUsecase.ts
  src/domain/repositories/smalltalk/IOpenQuestionRepository.ts
  src/infrastructure/repositories/smalltalk/SbOpenQuestionRepository.ts
Labels: :sparkles: Feat

#111 Feat/#110 openquestion delete
  src/app/admin/smalltalk/openquestion/page.tsx
  src/app/api/admin/smalltalk/openquestion/route.ts
  src/application/usecases/smalltalk/DeleteOpenQuestionUsecase.ts
  src/domain/repositories/smalltalk/IOpenQuestionRepository.ts
  src/infrastructure/repositories/smalltalk/SbOpenQuestionRepository.ts
Labels: :sparkles: Feat

#65 Feat/#56 DB 데이터 모델 재정의
  src/app/.gitkeep
  src/app/api/profile/route.ts
  src/application/usecases/profile/GetProfileUsecase.ts
  src/application/usecases/profile/PrivacySettingsUsecase.ts
  src/application/usecases/profile/UpdatePrivacySettingUsecase.ts
  src/application/usecases/profile/dtos/AboutMeDTO.ts
  src/application/usecases/profile/dtos/IsPublicDTO.ts
  src/application/usecases/profile/dtos/ProfileDTO.ts
  src/components/profile/AboutMe.Styled.tsx
  src/components/profile/AboutMe.tsx
  src/components/profile/PrivacyToggle.Styled.tsx
  src/components/profile/PrivacyToggle.tsx
  src/components/profile/ProfileActions.Styled.tsx
  src/components/profile/ProfileActions.tsx
  src/components/profile/ProfileHeader.Styled.tsx
  src/components/profile/ProfileHeader.tsx
  src/components/profile/ProfilePage.Styled.tsx
  src/components/profile/ProfilePage.tsx
  src/components/profile/Toggle.Styled.tsx
  src/components/profile/Toggle.tsx
  src/domain/entities/profile/IsPublic.ts
  src/domain/entities/profile/SNSInformation.ts
  src/domain/entities/profile/SelectedItem.ts
  src/domain/entities/profile/UserInput.ts
  src/domain/repositories/profile/IIsPublicRepository.ts
  src/domain/repositories/profile/ISNSRepository.ts
  src/domain/repositories/profile/IUserinputRepository.ts
  src/infrastructure/repositories/profile/SbIsPublicRepository.ts
  src/infrastructure/repositories/profile/SbSNSRepository.ts
  src/infrastructure/repositories/profile/SbUserinputRepository.ts
Labels: :bug: Bug, ♻️Refactor

#113 Refactor/admin openquestion hook 분리 , fetchClient 사용
  src/app/(anon)/smalltalks/select/page.tsx
  src/app/admin/smalltalk/openquestion/page.tsx
  src/components/admin/EditOpenQuestionTable.tsx
  src/components/admin/hook/UseModals.tsx
  src/components/admin/hook/UseOpenQuestion.tsx
  src/components/smaltalk/BalanceGame.tsx
  src/components/smaltalk/OpenQuestion.tsx
  src/utils/api/fetchClient.ts
Labels: ♻️Refactor

#116 Refactor/99 signup - 코드 리팩토링 및 회원 수정 페이지 컴포넌트 사용
  src/components/auth/SignUp.Styled.tsx
  src/components/auth/SignUpForm.tsx
  src/components/auth/signup/BirthDateSection.tsx
  src/components/auth/signup/EmailSection.tsx
  src/components/auth/signup/NameSection.tsx
  src/components/auth/signup/PasswordSection.tsx
  src/components/auth/signup/PhoneSection.tsx
  src/components/auth/signup/index.ts
  src/components/auth/useSignUpForm.tsx
  src/components/dashboard/DashBoard.Styled.tsx
  src/components/dashboard/DashBoard.tsx
  src/components/dashboard/InfoItem.Styled.tsx
  src/components/dashboard/InfoItem.tsx
  src/infrastructure/repositories/profile/SbUserinputRepository.ts
Labels: :sparkles: Feat, ♻️Refactor

#120 Feat/#115 Admin balancegame read
  src/app/admin/smalltalk/balancegame/page.tsx
  src/app/api/admin/smalltalk/balancegame/route.ts
  src/components/admin/AdminBalanceGame.Style.tsx
  src/components/admin/table/Table.Style.tsx
  src/components/admin/table/Table.tsx
Labels: :sparkles: Feat

#118 Refactor/66 ProfileHeader 컴포넌트 리팩토링
  src/app/api/profile/route.ts
  src/app/api/user/profile/route.ts
  src/app/page.tsx
  src/app/user/profile/page.tsx
  src/application/profile/dtos/AboutMeDTO.ts
  src/application/profile/dtos/PrivacySettingDTO.ts
  src/application/profile/usecases/GetAboutMeUsecase.ts
  src/application/profile/usecases/GetPrivacySettingsUsecase.ts
  src/application/profile/usecases/GetProfileDetailsUsecase.ts
  src/application/usecases/profile/IsPublicUsecase.ts
  src/application/usecases/profile/ProfileHeaderUsecase.ts
  src/application/usecases/profile/dtos/ProfileHeaderDTO.ts
  src/components/profile/ProfileHeader.Styled.tsx
  src/components/profile/ProfileHeader.tsx
  src/components/profile/ProfileImgFinder.tsx
  src/components/profile/ProfilePage.Styled.tsx
  src/components/profile/ProfilePage.tsx
  src/domain/repositories/profile/ISNSRepository.ts
  src/infrastructure/repositories/profile/SbUserinputRepository.ts
Labels: :bug: Bug, ♻️Refactor

#124 Feat/#121 balancegame create
  src/app/admin/smalltalk/balancegame/page.tsx
  src/app/api/admin/smalltalk/balancegame/route.ts
  src/application/usecases/smalltalk/CreateBalanceGame.ts
  src/components/admin/balancegamemodal/BalancegameModal.tsx
  src/domain/repositories/smalltalk/IBalancegameAnswerRepository.ts
  src/domain/repositories/smalltalk/IBalancegameQuestionRepository.ts
  src/infrastructure/repositories/smalltalk/SbBalancegameAnswerRepository.ts
  src/infrastructure/repositories/smalltalk/SbBalancegameQuestionRepository.ts
Labels: :sparkles: Feat

#126 Feat/125 balancegame update
  src/app/admin/smalltalk/balancegame/page.tsx
  src/app/api/admin/smalltalk/balancegame/route.ts
  src/application/usecases/smalltalk/CreateBalancegameUsecase.ts
  src/application/usecases/smalltalk/SmalltalkSubjectsUsecase.ts
  src/application/usecases/smalltalk/UpdateBalancegameAnswersUsecase.ts
  src/application/usecases/smalltalk/UpdateBalancegameQuestionUsecase.ts
  src/domain/repositories/smalltalk/IBalancegameAnswerRepository.ts
  src/domain/repositories/smalltalk/IBalancegameQuestionRepository.ts
  src/infrastructure/repositories/smalltalk/SbBalancegameAnswerRepository.ts
  src/infrastructure/repositories/smalltalk/SbBalancegameQuestionRepository.ts
Labels: :sparkles: Feat

#128 Feat/#127 balancegame delete
  src/app/admin/smalltalk/balancegame/page.tsx
  src/app/api/admin/smalltalk/balancegame/route.ts
  src/application/usecases/smalltalk/DeleteBalancegameUsecase.ts
  src/domain/repositories/smalltalk/IBalancegameAnswerRepository.ts
  src/domain/repositories/smalltalk/IBalancegameQuestionRepository.ts
  src/infrastructure/repositories/smalltalk/SbBalancegameAnswerRepository.ts
  src/infrastructure/repositories/smalltalk/SbBalancegameQuestionRepository.ts
Labels: :sparkles: Feat

#133 Refactor/#129 admin balancegame hook 분리
  src/app/admin/smalltalk/balancegame/page.tsx
  src/components/admin/BalancegameTable.tsx
  src/components/admin/hook/UseBalancegame.tsx
Labels: ♻️Refactor

#134 Refactor/#129 admin balancegame 검색창 누락
  src/app/admin/smalltalk/balancegame/page.tsx
Labels: ♻️Refactor

#137 Design/#136 회원탈퇴 완료 모달 생성
  src/components/withdraw/WithdrawModal.Styled.tsx
  src/components/withdraw/WithdrawModal.tsx
Labels: 💄Design

#138 Feat/117 dashboard detail
  src/app/api/user/dashboard/route.ts
  src/application/usecases/auth/GetUserUseCase.ts
  src/application/usecases/auth/SignUpUseCase.ts
  src/application/usecases/auth/UpdateUserUseCase.ts
  src/application/usecases/auth/dtos/UserResponseDto.ts
  src/application/usecases/auth/dtos/UserUpdateDto.ts
  src/components/dashboard/DashBoard.tsx
  src/components/dashboard/InfoItem.tsx
  src/components/withdraw/Withdraw.tsx
  src/domain/repositories/auth/IUserRepository.ts
  src/infrastructure/repositories/auth/SbUserRepository.ts
  src/utils/convert/convertToCase.ts
Labels: :sparkles: Feat

#141 Feat/#135 관리자 페이지 접근 제한
  src/app/admin/smalltalk/balancegame/page.tsx
  src/app/admin/smalltalk/openquestion/page.tsx
  src/app/admin/user/page.tsx
  src/app/api/admin/user/route.ts
  src/components/admin/hook/useAdminAuth.tsx
  src/components/common/modal.tsx
  src/infrastructure/repositories/profile/SbUserInputRepository.ts
  src/types/navBar.d.ts
Labels: :sparkles: Feat

#150 Design/84 findid-page-ui
  src/app/(anon)/findid/page.tsx
  src/app/(anon)/login/page.tsx
  src/components/auth/login/LoginForm.Styled.tsx
  src/components/auth/login/LoginForm.tsx
  src/components/auth/useLoginForm.tsx
  src/components/common/button/TextButton.tsx
  src/components/findid/FindID.Styled.tsx
  src/components/findid/FindID.tsx
  src/components/findid/useFindIDForm.tsx
  src/components/withdraw/Withdraw.tsx
Labels: :sparkles: Feat

#155 Refactor/#146 admin user hook 분리 및 usecase 파일 구조 변경
  src/app/admin/smalltalk/balancegame/page.tsx
  src/app/admin/smalltalk/openquestion/page.tsx
  src/app/admin/user/page.tsx
  src/app/api/admin/smalltalk/balancegame/route.ts
  src/app/api/admin/smalltalk/openquestion/route.ts
  src/app/api/admin/user/route.ts
  src/application/usecases/admin/balancegame/CreateBalancegameUsecase.ts
  src/application/usecases/admin/balancegame/DeleteBalancegameUsecase.ts
  src/application/usecases/admin/balancegame/UpdateBalancegameAnswersUsecase.ts
  src/application/usecases/admin/balancegame/UpdateBalancegameQuestionUsecase.ts
  src/application/usecases/admin/openquestion/CreateOpenQuestionUsecase.ts
  src/application/usecases/admin/openquestion/DeleteOpenQuestionUsecase.ts
  src/application/usecases/admin/openquestion/UpdateOpenQuestionUsecase.ts
  src/components/admin/UserTable.tsx
  src/components/admin/hook/UseAdminAuth.tsx
  src/components/admin/hook/UseDeleteUser.tsx
  src/components/admin/hook/UseFetchUsers.tsx
Labels: ♻️Refactor

#157 Feat/#151-BE-findEmail 기능구현 및 navBar제거
  src/app/(anon)/findid/page.tsx
  src/app/api/findemail/route.ts
  src/application/usecases/auth/FindEmailUseCase.ts
  src/components/common/LayoutContainer.tsx
  src/components/findemail/FindEmail.Styled.tsx
  src/components/findemail/FindEmail.tsx
  src/components/findemail/useFindEmailForm.tsx
  src/domain/repositories/auth/IUserRepository.ts
  src/infrastructure/repositories/auth/SbUserRepository.ts
Labels: :sparkles: Feat

#162 Design/158-sidebar
  package-lock.json
  package.json
  public/Icons/sidebarButton.svg
  src/app/(anon)/smalltalks/[id]/page.tsx
  src/components/common/LayoutContainer.tsx
  src/components/common/navbar/NavBar.Styled.tsx
  src/components/common/navbar/Navbar.tsx
  src/components/common/sidebar/Sidebar.tsx
  src/components/smaltalk/Select.Styled.tsx
  src/components/smaltalk/Suggest.Styled.tsx
  src/types/navBar.d.ts
Labels: 💄Design, 🚑!HotFix

#167 Feat/#165-Be findpw입력창을 통해 userId전달
  src/app/api/findemail/route.ts
  src/app/api/findepw/route.ts
  src/application/usecases/auth/GetUserIdUseCase.ts
  src/application/usecases/auth/dtos/UserIdRequestDto.ts
  src/domain/repositories/auth/IUserRepository.ts
  src/infrastructure/repositories/auth/SbUserRepository.ts
Labels: :sparkles: Feat
